# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#===============================================================================
# Site-wide settings

title: The Whole Daisy
subtitle: Dr. Daisy Sophia Hollman, Ph.D.
email: web@dsh.fyi
description: >- # this means to ignore newlines
  The personal and professional website of Dr. Daisy Sophia Hollman, Ph. D.  All
  opinions expressed here are my own and do not represent my employer.
domain: dsh.fyi
url: "https://dsh.fyi"
baseurl: "" # the subpath of your site, e.g. /blog
locale: "en-US"


#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Settings specific to Github Pages
# repository: "dhollman/dsh.fyi"

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Usernames, email, and other identifiers in general
name: &fullname Daisy Sophia Hollman
twitter_username: &twitter The_Whole_Daisy
github_username: &github dhollman

#===============================================================================
# Theme settings
# theme: minimal-mistakes-jekyll
# remote_theme: pages-themes/modernist@v0.2.0

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Minimal mistakes settings
# minimal_mistakes_skin: "dark"

#===============================================================================
# Output
destination: ./docs

#===============================================================================
# Serve options
port: 4000

#===============================================================================
# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-hacker
